language: node_js
node_js:
- '0.11'
addons:
  code_climate:
    repo_token: 36990b0731f2eae80071a87b7a1fb6f621b78937a1141bf475cce0cb30ef0467
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
  on:
    tags: true
    branches: true
