language: node_js
node_js:
- '0.11'
addons:
  code_climate:
    repo_token: 36990b0731f2eae80071a87b7a1fb6f621b78937a1141bf475cce0cb30ef0467 
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: KlXutjYZ4SVCqqcRrafwbR2rfptQinalMc4Uc3E0QR567ePWzFV9UI7VjrqwlD2wipWTGhnii73JjtfauJUkZKlTqEW6427SD4QIxO7UDkt+7d++za5m1GSK5x7VbVtII3s8QkKiarFCmf5mRyLNZWY7Fi3m/LRSmCklp0AYLzdsQcp9plrvY+91heCaK5JElFfYU1yysWCFGtvIo8gAy1lnqmkzErnahEqv5A62q09n8sgr8JLhpsU8Jxc8F5RUjJoPHcLgijoUeO8CdaTteGfcCe66XyJ5Eci/OY3Jc9Ust34fzjvYDbGKQmTkuf28nbB/mi765hBCT/ljRWKHlIEsIknKGMEhynsn5ZU96VDv/xlT86dg4B/4e0Y6KWvyGXcvV+CM/yFog/17eFTH0q+HHFat0D5qa4Jmyggp/OHeYrNV5jA9Y4G+rjwj1rd55yvcLdTD5F8RH6ZAMZfC6Y0Z8CV9uC4guDbznDgwbItg1gS3BHbgnSubo5GjqHp7m4r7wsdwPRHeXkTI239Il1uiwZhj+cdkXM2zIO4yXpjKGasnUqD1fBLfTYdPEAqzTUkIU83IIm/yNlXCSVTZAElimtU67w0u3Ephz9hv6XIeSuoOn+Gz/5sEQqWpGo7wr2Z5C5FazmhO7uf8LfhoLkK2ow3pWLO0sLenvTBLvqY=
  on:
    tags: true
    branches: true
